### PR TITLE
JSON-Serialize the list of selected ids

### PR DESCRIPTION
**Pull request by morlandi**
Solves "Object of type UUID is not JSON serializable" error with UUID pks

### CODE REVIEW

**Comment by morlandi** [comment]
No idea while the build is failing.

I'm using it with Django v 4.1.1 and Python 3.8.13 on both Mac and Linux 20

**Comment by abidibo** [comment]
@morlandi 

image

**Comment by morlandi** [comment]
mhh I see .. 

My bad, didn't run the unit tests locally. 

I'll update my PR soon, fixing the unit test; or, I could restore the original code and apply serialization only when catching the offending exception; later on, the de-serialization already does a defensive `if type(ids) == str` check; which one do you suggest ?

I'll be back in a few days, so in the meanwhile I'll test it in a real project

**Comment by morlandi** [comment]
@abidibo is the traceback of the failing test visible on github ?

**Comment by abidibo** [comment]
@morlandi I didn't have enough time to evaluate the code change, at a first glance I'd say that serializing (always) is a good idea.

As for the trace: you can see the logs of the jobs running on travis, it is not a trace though but just the output of the `python manage.py test` command:

https://github.com/otto-torino/django-admin-export-action/pull/5/checks?check_run_id=9166861622

From this page just click on the job number and you'll be redirected to the travis detail page

**Comment by morlandi** [comment]
@abidibo unit test fixed; also had to upgrade easy-thumbnails requirement in testapp to resolve a conflict with Django==4.1.1

**Comment by abidibo** [comment]
@morlandi merged in v0.3.1, thanks

**Pull request merged**
